[package]
name = "Auction"
version = "1.0.0"
authors = ["Osikhena James Oshomah"]

[addresses]
auction = "_"

[dependencies]
AptosFramework = {git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}
AptosTokenObjects = {git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects"}

[dev-dependencies]
